version: '3.8'

services:
  web:
    build: .
    image: abhishek838/paper_generator:latest
    container_name: paper_generator_web
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - REQUEST_COLLECTION=${REQUEST_COLLECTION}
      - PAPER_COLLECTION=${PAPER_COLLECTION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - NOTES_BUCKET_NAME=${NOTES_BUCKET_NAME}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - GOOGLE_FORM_WEBHOOK_URL=${GOOGLE_FORM_WEBHOOK_URL}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    volumes:
      - ./logging:/app/logging
      - ./temp_uploads:/app/temp_uploads
      - ./vectorstores:/app/vectorstores

volumes:
  mongodb_data: 